google:
  api:
    places:
      key: ${GOOGLE_MAP_API_KEY}
      details:
        url: "https://maps.googleapis.com/maps/api/place/details/json"
      geocoding:
        url: "https://maps.googleapis.com/maps/api/geocode/json"
      photo:
        url: "https://maps.googleapis.com/maps/api/place/photo"
